### ISSUE TITLE
Latest update doesn't load on 1.7.10 (protocolhack)

### ISSUE THREAD

**Issue by Kira07** [drtshock/ObsidianDestroyer#49]
Here is the error:

The plugin doesn't load on 1.7.10 (protocolhack) since the latest update, here is the error:

[01:39:00] [Server thread/INFO]: [ObsidianDestroyer] Enabling ObsidianDestroyer v4.4.11-SNAPSHOT
[01:39:00] [Server thread/INFO]: [ObsidianDestroyer] Creating config File.
[01:39:00] [Server thread/ERROR]: Error occurred while enabling ObsidianDestroyer v4.4.11-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/event/block/BlockExplodeEvent
   at com.drtshock.obsidiandestroyer.ObsidianDestroyer.onEnable(ObsidianDestroyer.java:137) ~[?:?]
   at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[spigot.jar:git-PaperSpigot-63fe5e4]
   at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [spigot.jar:git-PaperSpigot-63fe5e4]
   at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) [spigot.jar:git-PaperSpigot-63fe5e4]
   at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476) [spigot.jar:git-PaperSpigot-63fe5e4]
   at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) [spigot.jar:git-PaperSpigot-63fe5e4]
   at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:354) [spigot.jar:git-PaperSpigot-63fe5e4]
   at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:328) [spigot.jar:git-PaperSpigot-63fe5e4]
   at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:284) [spigot.jar:git-PaperSpigot-63fe5e4]
   at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:227) [spigot.jar:git-PaperSpigot-63fe5e4]
   at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:493) [spigot.jar:git-PaperSpigot-63fe5e4]
   at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-PaperSpigot-63fe5e4]
Caused by: java.lang.ClassNotFoundException: org.bukkit.event.block.BlockExplodeEvent
   at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-PaperSpigot-63fe5e4]
   at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-PaperSpigot-63fe5e4]
   at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_72]
   at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_72]
   ... 12 more

**Comment by drtshock** [comment]
Can you paste your full startup log? in a pastebin please

**Comment by Kira07** [comment]
Sure: http://pastebin.com/0X8quL7n

**Comment by drtshock** [comment]
It looks like you're not running what's on spigot. The line your error is pointing to is a blank line. Are you sure you are on the latest version from spigot? If not, try grabbing build 215 https://ci.drtshock.net/job/ObsidianDestroyer/

**Comment by Kira07** [comment]
As I mentionned in the title I'm using spigot 1.7.10 (protocolhaclk) so I'm
not on the latest version from spigot, I use build 1649.
I tryed with build 215 but it throws the same error.

2016-02-15 7:35 GMT+01:00 Trent Hensler <notifications@github.com>:

**Comment by drtshock** [comment]
Sorry, I'm taking about obsidiandestroyer. Can you paste the error from build 215?

**Comment by Kira07** [comment]
Here it is: http://pastebin.com/rFnv3TV3

2016-02-15 19:03 GMT+01:00 Trent Hensler <notifications@github.com>:

**Comment by Kira07** [comment]
Any update ?
Still having this startup error with the latest obsidiandestroyer update: http://pastebin.com/TJzSXfsd
Here is my paperspigot version: http://tcpr.ca/files/paperspigot/PaperSpigot-1.7.10-R0.1-SNAPSHOT-b43.jar

**Comment by Kira07** [comment]
Please ?

**Comment by squidicuzz** [comment]
Old issue.  Please submit a new ticket if this is still a problem..
